apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Values.azureIdentity.name }}
spec:
  type: {{ .Values.azureIdentity.type }}
  resourceID: {{ .Values.azureIdentity.resourceID }}
  clientID: {{ .Values.azureIdentity.clientID }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.azureIdentityBinding.name }}
spec:
  azureIdentity: {{ .Values.azureIdentity.name }}
  selector: {{ .Values.azureIdentityBinding.selector }}
